# Generated by Django 4.1.6 on 2023-05-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_subscriber_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
