# Generated by Django 4.1.5 on 2023-02-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_pays_profile_city_profile_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pays',
        ),
    ]
