# Generated by Django 4.1.6 on 2023-02-11 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_remove_profile_address_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_information',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile_information',
            name='Birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
