# Generated by Django 4.1.6 on 2023-05-10 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentification', '0013_remove_profile_information_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('profession', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='profile_photos')),
                ('cover', models.ImageField(upload_to='photo_cover')),
                ('location', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('rela_status', models.CharField(choices=[('Celibataire', 'CÉLIBATAIRE'), ('En Couple', 'EN COUPLE'), ('Divorcé', 'DIVORCE'), ('Veuf', 'VEUF'), ('Veuve', 'VEUVE')], max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile_information',
        ),
    ]
