# Generated by Django 4.1.6 on 2023-05-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0015_alter_profileinformation_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinformation',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
