# Generated by Django 4.1.5 on 2023-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
