# Generated by Django 4.1.6 on 2023-03-20 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_teammembers_date_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='commentaire',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
