# Generated by Django 4.1.5 on 2023-01-31 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='commentaire',
            new_name='message',
        ),
    ]
