# Generated by Django 4.1.6 on 2023-03-20 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reponse_commentaire_remove_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse_commentaire',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponse_commentaire',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
