# Generated by Django 4.1.6 on 2023-03-20 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_reponse_commentaire_email_reponse_commentaire_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse_commentaire',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='Comment', to='myapp.comment'),
        ),
    ]
